@startuml
skinparam shadowing false
skinparam monochrome true
skinparam TitleFontSize 20
skinparam sequenceTitleFontSize 20
skinparam sequenceTitleFontStyle plain

title coucou\n----

!define __ ➝
!define O •
!define DECS DECS
!define T TERME
!define F FACTEUR
state F : S __ PROG O

state Accept

state E0 : S __ O PROG
state E0 : PROG __ O DECS INSTRS
state E0 : DECS __ O DECS var IDS pv
state E0 : DECS __ O DECS const AFFECTS pv
state E0 : DECS __ O

state E1 : PROG __ DECS O INSTRS
state E1 : INSTRS __ O INSTRS lire id pv
state E1 : INSTRS __ O INSTRS ecrire EXP pv
state E1 : INSTRS __ O INSTRS id opaff pv
state E1 : INSTRS __ O
state E1 : DECS __ DECS O var IDS pv
state E1 : DECS __ DECS O const AFFECTS pv

state E2 : PROG __ DECS INSTRS O
state E2 : INSTRS __ INSTRS O lire id pv
state E2 : INSTRS __ INSTRS O ecrire EXP pv
state E2 : INSTRS __ INSTRS O id opaff EXP pv

state E3 : DECS __ DECS const O AFFECTS pv
state E3 : AFFECTS __ O AFFECTS v id eg num
state E3 : AFFECTS __ O id eg num

state E4 : DECS __ DECS var O IDS pv
state E4 : IDS __ O IDS v id
state E4 : IDS __ O id


state E5 : INSTRS __ INSTRS lire O id pv
state E6 : INSTRS __ INSTRS lire O EXP pv
state E6 : EXP __ O EXP add T
state E6 : EXP __ O EXP sous T
state E6 : EXP __ O T

state E7 : INSTRS INSTRS id O opaff

state E8 : DECS __ DECS const AFFECTS O pv
state E8 : AFFECTS __ AFFECTS O id eg num

state E10 : IDS __ id O

state E11 : DECS __ DECS var IDS O pv
state E11 : IDS __ IDS O v id

state E12 : DECS __ DECS var IDS pv O

state E13 : IDS __ IDS v O id

state E14 : IDS __ IDS v id O



[*] -> E0
E0 --> E1 : DECS
E1 --> E2 : INSTRS
F --> Accept : $
E0 --> F : PROG
E1 --> E3 : const
E2 --> E4 : var
E4 --> E11 : IDS
E11 --> E12 : pv
E4 --> E10 : id
E11 --> E13 : v
E13 --> E14 : id
E2 --> E5 : lire
E2 --> E6 : ecire
E2 --> E7 : id
E3 --> E8 : AFFECTS

@enduml
