@startuml
skinparam monochrome true
skinparam shadowing false
skinparam TitleFontSize 20
skinparam sequenceTitleFontSize 20
skinparam sequenceTitleFontStyle plain

skinparam class {
	BackgroundColor white
	BackgroundColor<<Warning>> lightblue
}

title Diagramme de classe

class Symbole{
	~int id
	+Symbole (int id)
	+operator int() const
}

class VirguleTerminal
class EgalTerminal
Class PointVirguleTerminal
class ConstTerminal
class VarTerminal
class EgalTerminal
class IdTerminal{
  +String IdName
}
class NumTerminal{
  +Int Value
}
class FinProgramme
class ErreurLexicale

class AffectationConstante{
	+AffectationConstante suivant
}
class Identificateur{
	+Identificateur suivant
}
class IdentificateurFacteur
class BlocDeclaration {
    +BlocDeclaration suivant
}
class DeclarationVariable
class DeclarationConstante
class Programme
class BlocInstruction {
    +BlocInstruction suivant
}
class InstructionLecture
class InstructionEcriture
class InstructionAffectation
class Expression
class ExpressionAdditive
class ExpressionSoustractive
class Terme
class ExpressionMult
class ExpressionDiv
class Facteur
class ExpressionParenthesee
class ConstanteNumerique

Symbole <|-- Programme
Symbole <|-- BlocDeclaration
Symbole <|-- BlocInstruction
Symbole <|-- AffectationConstante
Symbole <|-- Identificateur
Symbole <|-- Expression
Symbole <|-- VirguleTerminal
Symbole <|-- PointVirguleTerminal
Symbole <|-- ConstTerminal
Symbole <|-- VarTerminal
Symbole <|-- EgalTerminal
Symbole <|-- IdTerminal
Symbole <|-- NumTerminal
Symbole <|-- FinProgramme
Symbole <|-- ErreurLexicale

Programme *-- BlocDeclaration
Programme *-- BlocInstruction

BlocDeclaration <|-- DeclarationVariable
BlocDeclaration <|-- DeclarationConstante

Identificateur *-- DeclarationVariable

AffectationConstante *-- DeclarationConstante


BlocInstruction <|-- InstructionLecture
BlocInstruction <|-- InstructionEcriture
BlocInstruction <|-- InstructionAffectation

Expression <|-- ExpressionAdditive
Expression *-- ExpressionAdditive
Expression <|-- ExpressionSoustractive
Expression *-- ExpressionSoustractive
Expression <|-- Terme
Expression *-- ExpressionParenthesee

Terme *-- ExpressionAdditive
Terme *-- ExpressionSoustractive
Terme *-- ExpressionMult
Terme <|-- ExpressionMult
Terme *-- ExpressionDiv
Terme <|-- ExpressionDiv
Terme <|-- Facteur

Facteur <|-- ExpressionParenthesee
Facteur *-- ExpressionMult
Facteur *-- ExpressionDiv
Facteur <|-- ConstanteNumerique
Facteur <|-- IdentificateurFacteur

@endumlSymbole <|--