@startuml
skinparam monochrome true
skinparam shadowing false
skinparam TitleFontSize 20
skinparam sequenceTitleFontSize 20
skinparam sequenceTitleFontStyle plain

skinparam class {
	BackgroundColor white
	BackgroundColor<<Warning>> lightblue
}

title Structure du programme

class Symbole{
	~int id
	+Symbole (int id)
	+operator int() const
}

class Automate{

}

Automate -> Symbole : stack<Symbole*>\n pileSymboles
Automate --> Etat : stack<Etat*>\n pileEtats
Automate --> Lexeur : lexeur
Automate --> Programme : programme

class Etat{
    ~string nom
    +transition(Automate *, Symbole *)
}

class Programme{

 +AjouterDeclarationVar()
 +AjouterDeclarationConst()

}

Programme -- BlocDeclaration : HashMap<string,BlocDeclaration>\n dictDeclaration
Programme -- BlocInstruction : Vector<BlocInstruction>\n dictInstruction






class Lexeur{

}

@enduml